apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-pagamento-externo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-pagamento-externo
  template:
    metadata:
      labels:
        app: ms-pagamento-externo
    spec:
      containers:
        - name: ms-pagamento-externo
          image: 307946636040.dkr.ecr.sa-east-1.amazonaws.com/ms-pagamento-externo:latest
          ports:
            - containerPort: 5001