apiVersion: v1
kind: Service
metadata:
  name: ms-pagamento-externo-service
spec:
  selector:
    app: ms-pagamento-externo
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
  type: NodePort
